### ISSUE TITLE
Failing to load parser while predicting

### ISSUE THREAD

**Issue by MonsterAditya** [chen0040/keras-english-resume-parser-and-analyzer#16]
After training the resume parser with the sample data when I tried to run dl_based_parser_predict I got an issue on load the resumeparser. 
The issue was 
2019-11-28 15:25:02.165654: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-28 15:25:02.187682: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1800000000 Hz
2019-11-28 15:25:02.188639: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x654a2d0 executing computations on platform Host. Devices:
2019-11-28 15:25:02.188660: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-28 15:25:02.224289: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/python3.6/site-packages/numpy/lib/format.py", line 722, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

I am stuck in this. Please help

**Comment by suhasdatascientist** [comment]
Even I am facing the same error, any updates on this ?

**Comment by usman87626** [comment]
open the project in VSCode or any IDE you use:

Open Search bar for whole project and type: np.load()
It will show all the files that uses np.load().items() method
Pass "allow_pickle=True" as a argument to np.load() function everywhere in the code
Run the dl_based_parser_predict.py file and its fixed

Thanks :)
